/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.math.BigDecimal;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import logica.*;

import javax.swing.table.DefaultTableModel;
import logica.TipohabitacionLogica;
import modelo.Comodidadasociada;
import modelo.Tipohabitacion;

/**
 *
 * @author cristian
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    //DefaultTableModel modelo = new DefaultTableModel();
    public Admin() {
        initComponents();
        inRegisIdComodidad.enable(false);
        ComodidadasociadaLogica c = new ComodidadasociadaLogica();
        TipohabitacionLogica h = new TipohabitacionLogica();
        SalondeeventosLogica s = new SalondeeventosLogica();
        try {
            inRegisIdComodidad.setText(String.valueOf(c.consecutivoIDComodidad()));
        } catch (Exception ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            for (int i = 0; i < h.consultarTodos().size(); i++) {
                selectorTipoHabitacionH.addItem(h.consultarTodos().get(i).getNombretipohabitacion());
            }

        } catch (Exception ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
        inIdSalon.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTable9 = new javax.swing.JTable();
        jLabel31 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jButton17 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaHabitacion = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnConsultarHabitacion = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        inIdHabitacion = new javax.swing.JTextField();
        inConsultarHabitacion = new javax.swing.JTextField();
        btnRegistrarHabitacion = new javax.swing.JButton();
        selectorTipoHabitacionH = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        inPrecioSalon = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        inIdSalon = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        btnRegistrarSalon = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        inCapacidadSalon = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        inRegisIdComodidad = new javax.swing.JTextField();
        btnRegisComodidad = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tablaComodidad = new javax.swing.JTable();
        jLabel38 = new javax.swing.JLabel();
        inRegisNombreComodidad = new javax.swing.JTextField();
        inRegisPorcentajeComodidad = new javax.swing.JTextField();
        inConsulIdComodidad = new javax.swing.JTextField();
        btnBuscarComodidad = new javax.swing.JButton();
        btnModificarComodidad = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        selectorBusquedaComodidad = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        btnModificarTipoHabitacion = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        inNombreTipo = new javax.swing.JTextField();
        jScrollPane10 = new javax.swing.JScrollPane();
        tablaTipoHabitacion = new javax.swing.JTable();
        btnRegistrar = new javax.swing.JButton();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        inPrecioTipo = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        inConsultarTipoHabitacion = new javax.swing.JTextField();
        btnBuscarTipoHabitacion = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jTabbedPane6 = new javax.swing.JTabbedPane();
        jPanel20 = new javax.swing.JPanel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jButton20 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jPanel21 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jButton21 = new javax.swing.JButton();
        jDateChooser3 = new com.toedter.calendar.JDateChooser();
        jDateChooser4 = new com.toedter.calendar.JDateChooser();
        jPanel22 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jButton23 = new javax.swing.JButton();
        jDateChooser5 = new com.toedter.calendar.JDateChooser();
        jDateChooser6 = new com.toedter.calendar.JDateChooser();

        jLabel10.setText("jLabel10");

        jTable9.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane9.setViewportView(jTable9);

        jLabel31.setText("jLabel31");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Admin.png"))); // NOI18N

        jButton17.setText("Cerrar Sesion");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addGap(80, 80, 80))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton17)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(jButton17)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Home", jPanel1);

        jButton4.setText("Guardar cambios");

        tablaHabitacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Habitación", "Tipo de habitación"
            }
        ));
        jScrollPane2.setViewportView(tablaHabitacion);

        jLabel4.setText("ID Habitación:");

        jLabel1.setText("ID Habitación:");

        jLabel32.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel32.setText("REGISTRAR HABITACION");

        jLabel2.setText("Tipo de habitación:");

        btnConsultarHabitacion.setText("Buscar");
        btnConsultarHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarHabitacionActionPerformed(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel34.setText("CONSULTAR / MODIFICAR  HABITACION");

        inIdHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inIdHabitacionActionPerformed(evt);
            }
        });
        inIdHabitacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inIdHabitacionKeyTyped(evt);
            }
        });

        btnRegistrarHabitacion.setText("Registrar");
        btnRegistrarHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarHabitacionActionPerformed(evt);
            }
        });

        selectorTipoHabitacionH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectorTipoHabitacionHActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(133, 133, 133)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel1))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(inIdHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(selectorTipoHabitacionH, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                        .addGap(147, 147, 147)
                                        .addComponent(btnRegistrarHabitacion)
                                        .addGap(141, 141, 141))))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(216, 216, 216)
                                .addComponent(jLabel32))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(233, 233, 233)
                                .addComponent(jButton4))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel34)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(inConsultarHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnConsultarHabitacion)))))
                        .addGap(0, 72, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel32)
                .addGap(23, 23, 23)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(inIdHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(selectorTipoHabitacionH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegistrarHabitacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(jLabel34)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultarHabitacion)
                    .addComponent(jLabel4)
                    .addComponent(inConsultarHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Gestionar habitaciones", jPanel2);

        jLabel8.setText("ID Salón");

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jButton7.setText("Buscar");

        jButton8.setText("Guardar cambios");

        jLabel5.setText("ID Salon:");

        jLabel6.setText("Capacidad maxima:");

        jLabel35.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel35.setText("REGISTRAR SALON");

        jLabel36.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel36.setText("CONSULTAR / MODIFICAR  SALON");

        btnRegistrarSalon.setText("Registrar");
        btnRegistrarSalon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarSalonActionPerformed(evt);
            }
        });

        jLabel9.setText("Precio:");

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID Salón", "Capacidad Maxima", "Precio"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(inIdSalon, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel6)
                                                .addComponent(jLabel9))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(inPrecioSalon, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(inCapacidadSalon, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(141, 141, 141)
                                        .addComponent(btnRegistrarSalon)))
                                .addGap(158, 158, 158))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel35)
                                .addGap(220, 220, 220))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jButton8)
                                .addGap(222, 222, 222))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel36)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(jButton7)
                                .addGap(100, 100, 100))))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel35)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inIdSalon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(inCapacidadSalon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(inPrecioSalon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegistrarSalon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(jLabel36)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton8)
                .addGap(23, 23, 23))
        );

        jTabbedPane1.addTab("Gestionar salon de eventos", jPanel3);

        inRegisIdComodidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inRegisIdComodidadKeyTyped(evt);
            }
        });

        btnRegisComodidad.setText("Registrar");
        btnRegisComodidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisComodidadActionPerformed(evt);
            }
        });

        jLabel15.setText("Porcentaje Incremento:");

        tablaComodidad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Comodidad", "Nombre", "Porcentaje Incremento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(tablaComodidad);

        jLabel38.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel38.setText("CONSULTAR / MODIFICAR  COMODIDAD");

        inRegisNombreComodidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inRegisNombreComodidadActionPerformed(evt);
            }
        });
        inRegisNombreComodidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inRegisNombreComodidadKeyTyped(evt);
            }
        });

        inRegisPorcentajeComodidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inRegisPorcentajeComodidadKeyTyped(evt);
            }
        });

        inConsulIdComodidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inConsulIdComodidadActionPerformed(evt);
            }
        });
        inConsulIdComodidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inConsulIdComodidadKeyTyped(evt);
            }
        });

        btnBuscarComodidad.setText("Buscar");
        btnBuscarComodidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarComodidadActionPerformed(evt);
            }
        });

        btnModificarComodidad.setText("Guardar cambios");
        btnModificarComodidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarComodidadActionPerformed(evt);
            }
        });

        jLabel13.setText("ID Comodidad:");

        jLabel14.setText("Nombre:");

        jLabel37.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel37.setText("REGISTRAR COMODIDAD");

        selectorBusquedaComodidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID Comodidad", "Nombre" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(selectorBusquedaComodidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(inConsulIdComodidad, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBuscarComodidad)
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel37)
                        .addGap(207, 207, 207))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel14)
                                        .addComponent(jLabel13)
                                        .addComponent(jLabel15))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(inRegisIdComodidad)
                                            .addComponent(inRegisNombreComodidad, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(inRegisPorcentajeComodidad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGap(152, 152, 152)
                                    .addComponent(btnRegisComodidad)))
                            .addComponent(jLabel38))
                        .addGap(161, 161, 161))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(btnModificarComodidad)
                        .addGap(220, 220, 220))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel37)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inRegisIdComodidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inRegisNombreComodidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inRegisPorcentajeComodidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegisComodidad)
                .addGap(57, 57, 57)
                .addComponent(jLabel38)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inConsulIdComodidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarComodidad)
                    .addComponent(selectorBusquedaComodidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnModificarComodidad)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Gestionar comodidades asociadas", jPanel4);

        btnModificarTipoHabitacion.setText("Guardar cambios");
        btnModificarTipoHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarTipoHabitacionActionPerformed(evt);
            }
        });

        jLabel21.setText("Nombre:");

        jLabel41.setText("Precio:");

        inNombreTipo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inNombreTipoKeyTyped(evt);
            }
        });

        tablaTipoHabitacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre tipo de habitación", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane10.setViewportView(tablaTipoHabitacion);

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        jLabel42.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel42.setText("REGISTRAR TIPO HABITACION");

        jLabel43.setText("Nombre tipo de habitación:");

        inPrecioTipo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inPrecioTipoKeyTyped(evt);
            }
        });

        jLabel44.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel44.setText("CONSULTAR / MODIFICAR TIPO  HABITACION");

        inConsultarTipoHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inConsultarTipoHabitacionActionPerformed(evt);
            }
        });
        inConsultarTipoHabitacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inConsultarTipoHabitacionKeyTyped(evt);
            }
        });

        btnBuscarTipoHabitacion.setText("Buscar");
        btnBuscarTipoHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarTipoHabitacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(btnRegistrar))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel42)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel21)
                                .addComponent(jLabel41))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(inNombreTipo)
                                .addComponent(inPrecioTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel44)
                        .addGap(161, 161, 161))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel43)
                        .addGap(18, 18, 18)
                        .addComponent(inConsultarTipoHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscarTipoHabitacion)
                        .addGap(73, 73, 73))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(btnModificarTipoHabitacion)
                        .addGap(220, 220, 220))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane10)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel42)
                .addGap(27, 27, 27)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(inNombreTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(inPrecioTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegistrar)
                .addGap(95, 95, 95)
                .addComponent(jLabel44)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43)
                    .addComponent(inConsultarTipoHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarTipoHabitacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnModificarTipoHabitacion)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Gestionar tipo de habitacion", jPanel5);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lunes", "Martes", "Miercoles", "Jueves", "Viernes", "Sabado", "Domingo" }));

        jLabel24.setText("Dia de la semana:");

        jLabel25.setText("Desde:");

        jLabel26.setText("Hasta:");

        jButton20.setText("Generar Reporte");

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel20Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(45, 45, 45)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(49, 49, 49))
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(jButton20))
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel24)
                        .addGap(27, 27, 27)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(252, Short.MAX_VALUE))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel25)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addGap(1, 1, 1)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel26)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton20)
                .addGap(0, 280, Short.MAX_VALUE))
        );

        jTabbedPane6.addTab("Numero de clientes registrados", jPanel20);

        jLabel27.setText("Desde:");

        jLabel28.setText("Hasta:");

        jButton21.setText("Generar Reporte");

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel21Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addGap(45, 45, 45)
                        .addComponent(jDateChooser3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel21Layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jDateChooser4, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(71, 71, 71)
                .addComponent(jButton21)
                .addContainerGap(162, Short.MAX_VALUE))
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel21Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel27)
                            .addComponent(jDateChooser3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel21Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jButton21)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel28)
                    .addComponent(jDateChooser4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(290, Short.MAX_VALUE))
        );

        jTabbedPane6.addTab("Porcentaje de registros de hospedaje", jPanel21);

        jLabel29.setText("Desde:");

        jLabel30.setText("Hasta:");

        jButton23.setText("Generar Reporte");

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel22Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addGap(45, 45, 45)
                        .addComponent(jDateChooser5, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel22Layout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jDateChooser6, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(71, 71, 71)
                .addComponent(jButton23)
                .addContainerGap(162, Short.MAX_VALUE))
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel22Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel29)
                            .addComponent(jDateChooser5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel22Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jButton23)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel30)
                    .addComponent(jDateChooser6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(290, Short.MAX_VALUE))
        );

        jTabbedPane6.addTab("Porcentajes de reserva", jPanel22);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane6)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane6)
        );

        jTabbedPane1.addTab("Generar reportes", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inConsulIdComodidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inConsulIdComodidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inConsulIdComodidadActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:

        this.dispose();
        VentanaLoggin v = new VentanaLoggin();
        v.setVisible(true);
    }//GEN-LAST:event_jButton17ActionPerformed

    private void inConsultarTipoHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inConsultarTipoHabitacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inConsultarTipoHabitacionActionPerformed

    private void btnConsultarHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarHabitacionActionPerformed
        // TODO add your handling code here:

        HabitacionLogica h = new HabitacionLogica();
        try {
            Object[] fila = new Object[2];
            fila[0] = h.consultarHabitacion(inConsultarHabitacion.getText().toUpperCase()).getIdhabitacion();
            fila[1] = h.consultarHabitacion(inConsultarHabitacion.getText().toUpperCase()).getNombretipohabitacion();
            DefaultTableModel modelo = (DefaultTableModel) tablaHabitacion.getModel();
            modelo.setNumRows(0);
            modelo.addRow(fila);
        } catch (Exception ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnConsultarHabitacionActionPerformed

    private void btnBuscarTipoHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarTipoHabitacionActionPerformed
        String a = inConsultarTipoHabitacion.getText().toUpperCase();
        TipohabitacionLogica t = new TipohabitacionLogica();
        Tipohabitacion th = new Tipohabitacion();
        th.setNombretipohabitacion(a);
        if (!inConsultarTipoHabitacion.getText().equals("")) {
            try {
                Object[] fila = new Object[2];
                fila[0] = t.consultarTipoHabitacion(th).getNombretipohabitacion();
                fila[1] = t.consultarTipoHabitacion(th).getPrecio();
                DefaultTableModel modelo = (DefaultTableModel) tablaTipoHabitacion.getModel();
                modelo.setNumRows(0);
                modelo.addRow(fila);
            } catch (Exception ex) {
                System.err.println(ex.getMessage());
                JOptionPane.showMessageDialog(this, "No existe el nombre ingresado. Intentelo de nuevo.");
                inConsultarTipoHabitacion.setText("");
                DefaultTableModel modelo = (DefaultTableModel) tablaTipoHabitacion.getModel();
                modelo.setNumRows(0);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Debe ingresar un dato de busqueda.");
        }

    }//GEN-LAST:event_btnBuscarTipoHabitacionActionPerformed

    private void btnRegisComodidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisComodidadActionPerformed
        // TODO add your handling code here:
        ComodidadasociadaLogica c = new ComodidadasociadaLogica();
        BigDecimal b;
        if (inRegisPorcentajeComodidad.getText().equals("")) {
            b = BigDecimal.ZERO;
        } else {
            b = BigDecimal.valueOf(Double.parseDouble(inRegisPorcentajeComodidad.getText()) / 100);
        }
        if (!b.equals(BigDecimal.ZERO)
                && !inRegisPorcentajeComodidad.getText().equals("0")
                && !inRegisNombreComodidad.getText().equals("")) {
            try {
                Comodidadasociada s = new Comodidadasociada();
                s.setNombre(inRegisNombreComodidad.getText().toUpperCase());
                s.setPorcentajeincremento(b);
                c.registrarComodidad(s);
                JOptionPane.showMessageDialog(this, "Comodidad registrada");
            } catch (Exception ex) {
                System.err.println(ex.toString());
                String a = ex.getMessage();
                if (a.equals("empty String")) {
                    JOptionPane.showMessageDialog(this, "Ningun campo puede estar vacio. Intentelo de nuevo.");
                } else {
                    JOptionPane.showMessageDialog(this, "Comodidad registrada ya existe.");
                }
            }
        } else {
            if (inRegisPorcentajeComodidad.getText().equals("0")) {
                JOptionPane.showMessageDialog(this, "El porcentaje de incremento debe ser igual o mayor que 1.");
            } else {
                JOptionPane.showMessageDialog(this, "Ningun campo debe estar vacio. Intentelo de nuevo.");
            }
        }
        inRegisNombreComodidad.setText("");
        inRegisPorcentajeComodidad.setText("");
        try {
            inRegisIdComodidad.setText(String.valueOf(c.consecutivoIDComodidad()));
        } catch (Exception ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRegisComodidadActionPerformed

    private void btnRegistrarHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarHabitacionActionPerformed
        // TODO add your handling code here:
        TipohabitacionLogica h = new TipohabitacionLogica();
        try {
            for (int i = 0; i < h.consultarTodos().size(); i++) {
                selectorTipoHabitacionH.addItem(h.consultarTodos().get(i).getNombretipohabitacion());
            }

        } catch (Exception ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRegistrarHabitacionActionPerformed

    private void btnRegistrarSalonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarSalonActionPerformed
        // TODO add your handling code here:
        SalondeeventosLogica s = new SalondeeventosLogica();
        try {
            s.registrarSalon(Integer.parseInt(inCapacidadSalon.getText()), Double.parseDouble(inPrecioSalon.getText()));
        } catch (Exception ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRegistrarSalonActionPerformed

    private void inNombreTipoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inNombreTipoKeyTyped
        char c = evt.getKeyChar();
        System.out.println(c);
        if (inNombreTipo.getText().length() >= 20) {
            evt.consume();
        }
        if (!Character.isLetter(c) && !Character.isSpaceChar(c)) {
            evt.consume();
        } // TODO add your handling code here:
    }//GEN-LAST:event_inNombreTipoKeyTyped

    private void inPrecioTipoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inPrecioTipoKeyTyped
        char c = evt.getKeyChar();
        if (inPrecioTipo.getText().length() >= 7) {
            evt.consume();
        }
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_inPrecioTipoKeyTyped

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        TipohabitacionLogica tipo = new TipohabitacionLogica();
        if (!inNombreTipo.getText().equals("")) {
            try {
                Tipohabitacion t = new Tipohabitacion();
                t.setNombretipohabitacion(inNombreTipo.getText().toUpperCase());
                t.setPrecio(Double.parseDouble(inPrecioTipo.getText()));
                tipo.registrarTipoHabitacion(t);// TODO add your handling code here:
                JOptionPane.showMessageDialog(this, "Tipo de habitacion registrado correctamente");
                inNombreTipo.setText("");
                inPrecioTipo.setText("");

            } catch (Exception ex) {
                String a = ex.getMessage();
                if (a.equals("empty String")) {
                    JOptionPane.showMessageDialog(this, "Debe ingresar todos los campos.");
                    inNombreTipo.setText("");
                    inPrecioTipo.setText("");
                } else {
                    JOptionPane.showMessageDialog(this, "El tipo de habitacion ingresado ya existe.");
                    inNombreTipo.setText("");
                    inPrecioTipo.setText("");
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Debe ingresar todos los campos.");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void inConsultarTipoHabitacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inConsultarTipoHabitacionKeyTyped
        char c = evt.getKeyChar();
        System.out.println(c);
        if (inConsultarTipoHabitacion.getText().length() >= 20) {
            evt.consume();
        }
        if (!Character.isLetter(c) && !Character.isSpaceChar(c)) {
            evt.consume();
        }  // TODO add your handling code here:
    }//GEN-LAST:event_inConsultarTipoHabitacionKeyTyped

    private void inRegisNombreComodidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inRegisNombreComodidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inRegisNombreComodidadActionPerformed

    private void btnBuscarComodidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarComodidadActionPerformed
        String a = inConsulIdComodidad.getText().toUpperCase();
        if (a.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese un dato para consultar.");
            return;
        }
        ComodidadasociadaLogica t = new ComodidadasociadaLogica();
        if (selectorBusquedaComodidad.getSelectedItem().toString() == "Nombre") {
            try {
                DefaultTableModel modelo = (DefaultTableModel) tablaComodidad.getModel();
                modelo.setNumRows(0);
                if (!t.consultarTodos().isEmpty()) {
                    for (int i = 0; i < t.consultarTodos().size(); i++) {
                        if (t.consultarTodos().get(i).getNombre().equals(a)) {
                            Object[] fila = new Object[3];
                            fila[0] = t.consultarTodos().get(i).getIdcomodidad();
                            fila[1] = t.consultarTodos().get(i).getNombre();
                            fila[2] = t.consultarTodos().get(i).getPorcentajeincremento();
                            modelo.addRow(fila);
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "No existe comodidad asociada que tenga el nombre que ha ingresado. Intentelo de nuevo.");
                    inConsulIdComodidad.setText("");
                }

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "No existe comodidad asociada que tenga el nombre que ha ingresado. Intentelo de nuevo.");
                inConsulIdComodidad.setText("");
            }
        } else if (selectorBusquedaComodidad.getSelectedItem().toString() == "ID Comodidad") {
            try {
                Comodidadasociada r = new Comodidadasociada();
                r.setIdcomodidad(Integer.parseInt(a));
                Object[] fila = new Object[3];
                fila[0] = t.consultarComodidad(r).getIdcomodidad();
                fila[1] = t.consultarComodidad(r).getNombre();
                fila[2] = t.consultarComodidad(r).getPorcentajeincremento();
                DefaultTableModel modelo = (DefaultTableModel) tablaComodidad.getModel();
                modelo.setNumRows(0);
                modelo.addRow(fila);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "No existe comodidad asociada que tenga el ID que ha ingresado. Intentelo de nuevo.");
                inConsulIdComodidad.setText("");
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarComodidadActionPerformed

    private void inRegisIdComodidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inRegisIdComodidadKeyTyped
        char c = evt.getKeyChar();
        System.out.println(c);
        if (inRegisIdComodidad.getText().length() >= 4) {
            evt.consume();
        }
        if (!Character.isDigit(c)) {
            evt.consume();
        }    // TODO add your handling code here:
    }//GEN-LAST:event_inRegisIdComodidadKeyTyped

    private void inRegisNombreComodidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inRegisNombreComodidadKeyTyped
        char c = evt.getKeyChar();
        System.out.println(c);
        if (inRegisNombreComodidad.getText().length() >= 20) {
            evt.consume();
        }
        if (!Character.isLetter(c) && !Character.isSpaceChar(c)) {
            evt.consume();
        }   // TODO add your handling code here:
    }//GEN-LAST:event_inRegisNombreComodidadKeyTyped

    private void inRegisPorcentajeComodidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inRegisPorcentajeComodidadKeyTyped
        char c = evt.getKeyChar();
        System.out.println(c);
        if (inRegisPorcentajeComodidad.getText().length() >= 2) {
            evt.consume();
        }
        if (!Character.isDigit(c)) {
            evt.consume();
        } // TODO add your handling code here:
    }//GEN-LAST:event_inRegisPorcentajeComodidadKeyTyped

    private void inConsulIdComodidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inConsulIdComodidadKeyTyped
        char c = evt.getKeyChar();
        System.out.println(c);
        if (selectorBusquedaComodidad.getSelectedItem().toString() == "Nombre") {
            if (inRegisNombreComodidad.getText().length() >= 20) {
                evt.consume();
            }
            if (!Character.isLetter(c) && !Character.isSpaceChar(c)) {
                evt.consume();
            }
        } else if (selectorBusquedaComodidad.getSelectedItem().toString() == "ID Comodidad") {
            if (inRegisNombreComodidad.getText().length() >= 4) {
                evt.consume();
            }
            if (!Character.isDigit(c)) {
                evt.consume();
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_inConsulIdComodidadKeyTyped

    private void btnModificarTipoHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarTipoHabitacionActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) tablaTipoHabitacion.getModel();
        Tipohabitacion th = new Tipohabitacion();
        if (tablaTipoHabitacion.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un tipo de habitacion de la tabla.");
        } else {
            try {
                System.out.println(tablaTipoHabitacion.getSelectedRow());
                th.setNombretipohabitacion(modelo.getValueAt(tablaTipoHabitacion.getSelectedRow(), 0).toString());
                TipohabitacionLogica l = new TipohabitacionLogica();
                Tipohabitacion t = l.consultarTipoHabitacion(th);
                t.setPrecio(Double.parseDouble(modelo.getValueAt(tablaTipoHabitacion.getSelectedRow(), 1).toString()));
                System.out.println(modelo.getValueAt(tablaTipoHabitacion.getSelectedRow(), 0).toString());
                try {
                    l.modificarTipoHAbitacion(t);
                } catch (Exception ex) {
                    Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (Exception ex) {
                Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnModificarTipoHabitacionActionPerformed

    private void btnModificarComodidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarComodidadActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) tablaComodidad.getModel();
        Comodidadasociada c = new Comodidadasociada();
        
        if (tablaComodidad.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione una comodidad asociada de la tabla.");
        } else {
            try {
                System.out.println(tablaComodidad.getSelectedRow());
                c.setIdcomodidad(Integer.parseInt(modelo.getValueAt(tablaComodidad.getSelectedRow(), 0).toString()));
                ComodidadasociadaLogica l = new ComodidadasociadaLogica();
                Comodidadasociada t = l.consultarComodidad(c);
                t.setNombre(modelo.getValueAt(tablaComodidad.getSelectedRow(), 1).toString().toUpperCase());
                t.setPorcentajeincremento(BigDecimal.valueOf(Double.parseDouble(modelo.getValueAt(tablaComodidad.getSelectedRow(), 2).toString())));
                try {
                    l.modificarComodidad(t);
                } catch (Exception ex) {
                    Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (Exception ex) {
                Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarComodidadActionPerformed

    private void inIdHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inIdHabitacionActionPerformed
       
    }//GEN-LAST:event_inIdHabitacionActionPerformed

    private void inIdHabitacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inIdHabitacionKeyTyped
 char c = evt.getKeyChar();
        System.out.println(c);
        if (inRegisIdComodidad.getText().length() >= 4) {
            evt.consume();
        }
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_inIdHabitacionKeyTyped

    private void selectorTipoHabitacionHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectorTipoHabitacionHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectorTipoHabitacionHActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarComodidad;
    private javax.swing.JButton btnBuscarTipoHabitacion;
    private javax.swing.JButton btnConsultarHabitacion;
    private javax.swing.JButton btnModificarComodidad;
    private javax.swing.JButton btnModificarTipoHabitacion;
    private javax.swing.JButton btnRegisComodidad;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnRegistrarHabitacion;
    private javax.swing.JButton btnRegistrarSalon;
    private javax.swing.JTextField inCapacidadSalon;
    private javax.swing.JTextField inConsulIdComodidad;
    private javax.swing.JTextField inConsultarHabitacion;
    private javax.swing.JTextField inConsultarTipoHabitacion;
    private javax.swing.JTextField inIdHabitacion;
    private javax.swing.JTextField inIdSalon;
    private javax.swing.JTextField inNombreTipo;
    private javax.swing.JTextField inPrecioSalon;
    private javax.swing.JTextField inPrecioTipo;
    private javax.swing.JTextField inRegisIdComodidad;
    private javax.swing.JTextField inRegisNombreComodidad;
    private javax.swing.JTextField inRegisPorcentajeComodidad;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox<String> jComboBox2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private com.toedter.calendar.JDateChooser jDateChooser3;
    private com.toedter.calendar.JDateChooser jDateChooser4;
    private com.toedter.calendar.JDateChooser jDateChooser5;
    private com.toedter.calendar.JDateChooser jDateChooser6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane6;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable9;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JComboBox<String> selectorBusquedaComodidad;
    private javax.swing.JComboBox<String> selectorTipoHabitacionH;
    private javax.swing.JTable tablaComodidad;
    private javax.swing.JTable tablaHabitacion;
    private javax.swing.JTable tablaTipoHabitacion;
    // End of variables declaration//GEN-END:variables
}
